# Generated by Django 5.0.3 on 2024-03-31 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alumno_profesor_alter_curso_nombre_alumno_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(default='', max_length=256)),
                ('nombre', models.CharField(max_length=256)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCoder.curso')),
            ],
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
