# Generated by Django 5.0.3 on 2024-03-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_alter_alumno_apellido_alter_alumno_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
