# Generated by Django 5.0.3 on 2024-03-31 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_alter_alumno_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesores',
            name='curso',
        ),
    ]
