# Generated by Django 5.0.3 on 2024-03-31 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_remove_profesores_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesores',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCoder.curso'),
        ),
    ]
